export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_ACTIVE_MAIN_TAB = 'SET_ACTIVE_MAIN_TAB';
export const SET_SERVERS =  'SET_SERVERS';
export const SET_INFINITE_SCROLLS = 'SET_INFINITE_SCROLLS';
export const SET_SNACK = 'SET_SNACK';
export const SET_FLOOD_WALL_POSTS = 'SET_FLOOD_WALL_POSTS';
export const SET_NEED_UPDATE_FLOOD_WALL = 'SET_NEED_UPDATE_FLOOD_WALL';
export const SET_STATE_DATA = 'SET_STATE_DATA';
export const SET_PAYS = 'SET_PAYS';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const UPDATE_SERVER = 'UPDATE_SERVER';
export const SET_MY_SERVERS = 'SET_MY_SERVERS';
export const SET_CUSTOM_SCROLL_POSITION = 'SET_CUSTOM_SCROLL_POSITION';
export const SET_ACTIVE_PAY = 'SET_ACTIVE_PAY';

export const SET_ACCOUNTS = 'SET_ACCOUNTS';